BOT:
  TOKEN: "6172666504:AAE7NHAasDmnXn1oBvcjHVh28aQqZhYDnOc"  # Get your bot token from @BotFater
AI:
  VERSION: "2023-03-15-preview"
  TYPE: "azure"
  ENGINE: "your azure openai deployment name"
  BASE: "https://docs-test-001.openai.azure.com/"
  TOKEN: "be***b63f"
MYSQL:
  DBHOST: 127.0.0.1
  DBPORT: 3306
  DBUSER: root
  DBPWD: dbpassword
  DBNAME: Cluster0
  DBCHAR: postgres://tufiatbi:uuel5uxW9dhBEfYz5WLHi2UclUzPyiSD@heffalump.db.elephantsql.com/tufiatbi

RATE_LIMIT:
  0: 10
  1: 30
  2: 300

CONTEXT_COUNT:
  0: 3
  1: 5
  2: 10

MAX_TOKEN:
  0: 256
  1: 1024
  2: 1024

TIME_SPAN: 3 #Minutes
DEVELOPER_CHAT_ID: 1391556668
